routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Backend\TeamController;
use App\Http\Controllers\Backend\AboutController;
use App\Http\Controllers\Backend\BlogsController;
use App\Http\Controllers\Backend\EventsController;
use App\Http\Controllers\Frontend\PagesController;
use App\Http\Controllers\Backend\AccountController;
use App\Http\Controllers\Backend\ContactController;
use App\Http\Controllers\Backend\GalleryController;
use App\Http\Controllers\Backend\ResultsController;
use App\Http\Controllers\Frontend\SearchController;
use App\Http\Controllers\Backend\CommentsController;
use App\Http\Controllers\Backend\MessagesController;
use App\Http\Controllers\Backend\ServicesController;
use App\Http\Controllers\Backend\CategoriesController;
use App\Http\Controllers\Backend\SliderImageController;
use App\Http\Controllers\Backend\StudyAbroadController;
use App\Http\Controllers\Backend\AnnouncementsController;
use App\Http\Controllers\Backend\TestPreparationsController;


Route::get('/', [PagesController::class, 'index'])->name('home');
Route::get('/about', [PagesController::class, 'about'])->name('about');
Route::get('/contact', [PagesController::class, 'contacts'])->name('about.contacts');
Route::get('/blogs', [PagesController::class, 'blogs'])->name('blogs');
Route::get('/blogs/{blog}/show', [PagesController::class, 'blogsShow'])->name('blogs.show');
Route::get('/blogs/{category}', [PagesController::class, 'blogsShowCategory'])->name('blogs.showcat');
Route::get('/services', [PagesController::class, 'services'])->name('about.services');
Route::get('/gallery', [PagesController::class, 'gallery'])->name('about.gallery');
Route::get('/services/{service}/show', [PagesController::class, 'servicesShow'])->name('about.services.show');
Route::get('/events', [PagesController::class, 'events'])->name('about.events');
Route::get('/teams', [PagesController::class, 'teams'])->name('about.teams');
Route::get('/events/{event}/show', [PagesController::class, 'eventsShow'])->name('about.events.show');
Route::get('/announcements', [PagesController::class, 'announcements'])->name('about.announcements');
Route::get('/announcements/{announcement}/show', [PagesController::class, 'announcementsShow'])->name('about.announcements.show');
Route::get('/studyabroads', [PagesController::class, 'studyabroads'])->name('studyabroads');
Route::get('/studyabroads/{studyabroad}/show', [PagesController::class, 'studyabroadsShow'])->name('studyabroads.show');
Route::get('/testpreparations', [PagesController::class, 'testpreparations'])->name('testpreparations');
Route::get('/testpreparations/{testpreparation}/show', [PagesController::class, 'testpreparationsShow'])->name('testpreparations.show');
Route::post('/contact-form', [PagesController::class, 'ajaxContactForm'])->name('contact.form');
Route::get('/search-form', [SearchController::class, 'search'])->name('search');


Route::group(['middleware' => ['auth'], 'prefix' => 'backend'], function () {

    Route::get('/pages/dashboard', function () { return view('backend.pages.dashboard'); })->name('backend.dashboard');

    // Blogs routes
    Route::get('/blogs', [BlogsController::class, 'index'])->name('backend.blogs');
    Route::get('/blogs/trashed', [BlogsController::class, 'getTrashed'])->name('backend.blogs.trashed');
    Route::get('/blogs/create', [BlogsController::class, 'create'])->name('backend.blogs.create');
    Route::post('/blogs/store', [BlogsController::class, 'store'])->name('backend.blogs.store');
    Route::get('/blogs/{blog}/show', [BlogsController::class, 'show'])->name('backend.blogs.show');
    Route::get('/blogs/{blog}/restore', [BlogsController::class, 'restore'])->name('backend.blogs.restore');
    Route::get('/blogs/{blog}/edit', [BlogsController::class, 'edit'])->name('backend.blogs.edit');
    Route::patch('/blogs/{blog}/update', [BlogsController::class, 'update'])->name('backend.blogs.update');
    Route::get('/blogs/{blog}/trash', [BlogsController::class, 'trash'])->name('backend.blogs.trash');
    Route::get('/blogs/{blog}/delete', [BlogsController::class, 'delete'])->name('backend.blogs.delete');
    Route::get('/blogs/delete-all', [BlogsController::class, 'deleteAll'])->name('backend.blogs.delete-all');
    Route::get('/blogs/trash-all', [BlogsController::class, 'trashAll'])->name('backend.blogs.trash-all');
    Route::get('/blogs/restore-all', [BlogsController::class, 'restoreAll'])->name('backend.blogs.restore-all');

    // Categories routes
    Route::get('/categories', [CategoriesController::class, 'index'])->name('backend.categories');
    Route::get('/categories/trashed', [CategoriesController::class, 'getTrashed'])->name('backend.categories.trashed');
    Route::get('/categories/create', [CategoriesController::class, 'create'])->name('backend.categories.create');
    Route::post('/categories/store', [CategoriesController::class, 'store'])->name('backend.categories.store');
    Route::get('/categories/{category}/show', [CategoriesController::class, 'show'])->name('backend.categories.show');
    Route::get('/categories/{category}/restore', [CategoriesController::class, 'restore'])->name('backend.categories.restore');
    Route::get('/categories/{category}/edit', [CategoriesController::class, 'edit'])->name('backend.categories.edit');
    Route::patch('/categories/{category}/update', [CategoriesController::class, 'update'])->name('backend.categories.update');
    Route::get('/categories/{category}/trash', [CategoriesController::class, 'trash'])->name('backend.categories.trash');
    Route::get('/categories/{category}/delete', [CategoriesController::class, 'delete'])->name('backend.categories.delete');

    // Announcments Routes
    Route::get('/announcements', [AnnouncementsController::class, 'index'])->name('backend.announcements');
    Route::get('/announcements/create', [AnnouncementsController::class, 'create'])->name('backend.announcements.create');
    Route::post('/announcements/store', [AnnouncementsController::class, 'store'])->name('backend.announcements.store');
    Route::get('/announcements/{announcement}/show', [AnnouncementsController::class, 'show'])->name('backend.announcements.show');
    Route::get('/announcements/{announcement}/edit', [AnnouncementsController::class, 'edit'])->name('backend.announcements.edit');
    Route::patch('/announcements/{announcement}/update', [AnnouncementsController::class, 'update'])->name('backend.announcements.update');
    Route::get('/announcements/{announcement}/delete', [AnnouncementsController::class, 'delete'])->name('backend.announcements.delete');


    // Events Routes
    Route::get('/events', [EventsController::class, 'index'])->name('backend.events');
    Route::get('/events/create', [EventsController::class, 'create'])->name('backend.events.create');
    Route::post('/events/store', [EventsController::class, 'store'])->name('backend.events.store');
    Route::get('/events/{event}/show', [EventsController::class, 'show'])->name('backend.events.show');
    Route::get('/events/{event}/edit', [EventsController::class, 'edit'])->name('backend.events.edit');
    Route::patch('/events/{event}/update', [EventsController::class, 'update'])->name('backend.events.update');
    Route::get('/events/{event}/delete', [EventsController::class, 'delete'])->name('backend.events.delete');


    // Study Abroad Routes
    Route::get('/studyabroads', [StudyAbroadController::class, 'index'])->name('backend.studyabroads');
    Route::get('/studyabroads/create', [StudyAbroadController::class, 'create'])->name('backend.studyabroads.create');
    Route::post('/studyabroads/store', [StudyAbroadController::class, 'store'])->name('backend.studyabroads.store');
    Route::get('/studyabroads/{studyabroad}/show', [StudyAbroadController::class, 'show'])->name('backend.studyabroads.show');
    Route::get('/studyabroads/{studyabroad}/edit', [StudyAbroadController::class, 'edit'])->name('backend.studyabroads.edit');
    Route::patch('/studyabroads/{studyabroad}/update', [StudyAbroadController::class, 'update'])->name('backend.studyabroads.update');
    Route::get('/studyabroads/{studyabroad}/delete', [StudyAbroadController::class, 'delete'])->name('backend.studyabroads.delete');


    // Test Preparations Routes
    Route::get('/testpreparations', [TestPreparationsController::class, 'index'])->name('backend.testpreparations');
    Route::get('/testpreparations/create', [TestPreparationsController::class, 'create'])->name('backend.testpreparations.create');
    Route::post('/testpreparations/store', [TestPreparationsController::class, 'store'])->name('backend.testpreparations.store');
    Route::get('/testpreparations/{testpreparation}/show', [TestPreparationsController::class, 'show'])->name('backend.testpreparations.show');
    Route::get('/testpreparations/{testpreparation}/edit', [TestPreparationsController::class, 'edit'])->name('backend.testpreparations.edit');
    Route::patch('/testpreparations/{testpreparation}/update', [TestPreparationsController::class, 'update'])->name('backend.testpreparations.update');
    Route::get('/testpreparations/{testpreparation}/delete', [TestPreparationsController::class, 'delete'])->name('backend.testpreparations.delete');

    // Update Password
    Route::get('/changepassword', [AccountController::class, 'password'])->name('backend.accounts.changepassword');
    Route::patch('/updatepassword', [AccountController::class, 'updateAccountPassword'])->name('backend.accounts.updatepassword');
    Route::get('/changeprofile', [AccountController::class, 'profile'])->name('backend.accounts.profile');
    Route::patch('/updateprofile', [AccountController::class, 'updateAccountProfile'])->name('backend.accounts.updateproflie');
    Route::get('/changeabout', [AboutController::class, 'aboutUs'])->name('backend.accounts.about');
    Route::patch('/updateabout/{about}', [AboutController::class, 'updateAboutUs'])->name('backend.accounts.updateabout');

    // Contacts Routes

app/Models/Blog.php
<?php

namespace App\Models;

use Spatie\Searchable\Searchable;
use Spatie\Searchable\SearchResult;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Database\Eloquent\Factories\HasFactory;

class Blog extends Model implements Searchable
{
    use HasFactory;
    use SoftDeletes;

    protected $dates = ['deleted_at'];

    protected $fillable = [
        'title',
        'meta_title',
        'meta_description',
        'meta_tags',
		'content',
		'slug',
        'image',
        'category_id',
        'is_featured',
        'is_trending',
        'views'
    ];

    // Use Slug instead of ID
    public function getRouteKeyName()
    {
        return 'slug';
    }

    public function getFeaturedOrTrending($value)
    {
        if($value) {
            $value = 1;
            return $value;
        } else {
            $value = 0;
            return $value;
        }
    }

    public function incrementViewsCount($blog) {
        DB::table('blogs')->whereId($blog->id)->increment('views');
    }


    public function getViewsAttribute($value)
    {
        if($value > 500){
            $views = [
                'number_of_views' => $value,
                'views_status' => 'Most Viewed'
            ];
        } elseif ($value > 200) {
            $views = [
                'number_of_views' => $value,
                'views_status' => 'Average Viewed'
            ];
        } else {
            $views = [
                'number_of_views' => $value,
                'views_status' => 'Normal Viewed'
            ];
        }
        return $views;
    }


    public function getCreatedAtAttribute($value) {
        $timestamp = strtotime($value);
        //Uppercase letters gives day, month in language(Jan, Third, etc)
        $year = date('Y', $timestamp);
        $month = date('M', $timestamp);
        //lowercase letters gives day, month in numbers(1, 3, etc)
        $day = date('d', $timestamp);

        $date = [
            'year' => $year,
            'month' => $month,
            'day'   => $day
        ];
        return $date;
    }

    public function category()
    {
        return $this->belongsTo(Category::class);
    }

    public function comments()
    {
        return $this->hasMany(Comment::class);
    }

    public function commentsCount() 
    {
        return $this->comments() 
            ->selectRaw('blog_id, count(*) as aggregate')
            ->groupBy('blog_id');
    }

    public function getSearchResult(): SearchResult
    {
        $url = route('blogs.show', $this->slug);

        return new SearchResult(
            $this,
            $this->title,
            $url
         );
    }

    public function getOnlyTitlesMetas()
    {
        $titles = $this->select('title', 'meta_title', 'meta_description', 'meta_tags')->get();
        return $titles;
    }
}

app/Http/Controllers/Frontend/SearchController.php
<?php

namespace App\Http\Controllers\Frontend;

use App\Models\Blog;
use App\Models\Team;
use App\Models\Event;
use App\Models\Service;
use App\Models\Category;
use App\Models\Announcement;
use Illuminate\Http\Request;
use Spatie\Searchable\Search;
use App\Http\Controllers\Controller;

class SearchController extends Controller
{
    public function search(Request $request)
    {
        $q = $request->input('query');
        $searchResults = (new Search())
            ->registerModel(Category::class, 'name')
            ->registerModel(Blog::class, 'title')
            ->registerModel(Team::class, 'name')
            ->registerModel(Service::class, 'service_description')
            ->registerModel(Event::class, ['title', 'description'])
            ->registerModel(Announcement::class, ['title', 'description'])
            ->limitAspectResults(200)
            ->perform($q);

        return view('frontend.pages.search', compact('searchResults'));
    }
}

resources/views/frontend/partials/_blogs.blade.php
@foreach($blogs as $blog)   
@endforeach
@if(isset($blogs) && $blogs->count() > 0)
    <!--blog-text-section-->
    <section class="ttm-row blog-text-section ttm-bgcolor-grey mt_120 res-991-mt-0 clearfix">
        <div class="container">
            <!-- row -->
            <div class="row">
                <div class="col-lg-12 col-md-12">
                    <!-- section-title -->
                    <div class="section-title style2 clearfix">
                        <div class="title-header">
                            <h5>Our latest News</h5>
                            <h2 class="title">Read Our Latest Blogs &amp; News</h2>
                        </div>
                        <div class="title-desc"><span class="quote-title">Quote of the day : </span> ❝{{ $q }}❞</div>
                    </div><!-- section-title end -->
                </div>
            </div><!-- row end -->
        </div>
    </section>
    <!--blog-text-section end-->

    <!--blog-section-->
    <section class="ttm-row blog-section home-blog-section clearfix">
        <div class="container">
            <!-- row -->
            <div class="row">
                <!-- post-slide -->
                <div class="post-slide owl-carousel owl-theme owl-loaded " data-item="3" data-nav="false" data-dots="false" data-auto="false">
                    <!-- featured-imagebox-post -->
                    @foreach($blogs as $blog)
                    <div class="featured-imagebox featured-imagebox-post box-shadow">
                        <div class="featured-thumbnail">
                            <img class="img-fluid" src="{{ asset(imagePath($blog->image, 'blogs')) }}" alt=""{{ $blog->title }}>
                            <div class="featured-icon">
                                <div class="ttm-icon ttm-icon_element-fill ttm-icon_element-background-color-skincolor ttm-icon_element-size-xs">
                                    <i class="ti ti-pencil"></i>
                                </div>
                            </div>
                        </div>
                        <div class="featured-content featured-content-post">
                            <div class="post-title featured-title">
                                <h5><a href="{{ route('blogs.show', $blog) }}">{{ Str::limit($blog->title, 50) }}</a></h5>
                            </div>
                            <div class="post-meta">
                                <span class="ttm-meta-line"><i class="fa fa-calendar"></i>{{ $blog->created_at['month'] }} {{ $blog->created_at['day'] }},
                                    {{ $blog->created_at['year'] }}</span>
                                <span class="ttm-meta-line"><i class="fa fa-eye"></i>{{ $blog->views['number_of_views'] }}</span>

                            </div>
                        </div>
                    </div>
                    @endforeach
                    <!-- featured-imagebox-post end -->
                </div>
            </div><!-- row end-->
        </div>
    </section>
    <!--blog-section end-->
@endif

resources/views/frontend/partials/_footer.blade.php
        <!--footer start-->
        <footer class="footer widget-footer clearfix">
            <div class="first-footer">
                <div class="container">
                    <div class="row">
                        <div class="col-lg-12 text-center">
                            <div class="first-footer-inner">
                                <div class="footer-logo">
                                    <img id="footer-logo-img" class="img-center" src="{{ asset(imagePath($site_logo, 'abouts')) }}" alt="{{ $about->site_name }}">

                                </div>
                                <div class="row no-gutters footer-box">
                                    <div class="col-md-4 widget-area">
                                        <div class="featured-box text-center">
                                            <div class="featured-content">
                                                <div class="featured-title">
                                                    <h5>Our Address</h5>
                                                </div>
                                                <div class="featured-desc">
                                                    <p>{{ $about->address }}</p>
                                                    <p>{{ $about->address_one }}</p>

                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-md-4 widget-area">
                                        <div class="featured-box text-center">
                                            <div class="featured-content">
                                                <div class="featured-title">
                                                    <h5>Talk To Expert</h5>
                                                </div>
                                                <div class="featured-desc">
                                                    <p>{{ $about->contact_number_one }} , {{ $about->contact_number_two }}</p>
                                                    <p>{{ $about->contact_number_three }}</p>

                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-md-4 widget-area">
                                        <div class="featured-box text-center">
                                            <div class="featured-content">
                                                <div class="featured-title">
                                                    <h5>Email Us</h5>
                                                </div>
                                                <div class="featured-desc">
                                                    <p>{{ $about->email_one }}</p>
                                                    <p>{{ $about->email_two }}</p>

                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="row no-gutters">
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="second-footer ttm-textcolor-white">
                <div class="container">
                    <div class="row">
                        <div class="col-xs-12 col-sm-12 col-md-6 col-lg-3 widget-area">
                            <div class="widget widget_text  clearfix">
                                <h3 class="widget-title">About {{ $about->site_name }}</h3>
                                <div class="textwidget widget-text">
                                    {{ Str::limit($about->site_description, '200') }}
                                    <br><br>
                                    <div class="social-icons circle social-hover">
                                        <ul class="list-inline">
                                            <li class="social-facebook"><a class="tooltip-top" target="_blank" href="{{ $about->facebook }}"
                                                    data-tooltip="Facebook"><i class="fa fa-facebook"
                                                        aria-hidden="true"></i></a></li>
                                            <li class="social-twitter"><a class="tooltip-top" target="_blank" href="{{ $about->twitter }}"

                                                    data-tooltip="Twitter"><i class="fa fa-twitter"
                                                        aria-hidden="true"></i></a></li>
                                            <li class="social-instagram"><a class=" tooltip-top" target="_blank" href="{{ $about->instagram }}"
                                                    data-tooltip="instagram"><i class="fa fa-instagram"
                                                        aria-hidden="true"></i></a></li>
                                            <li class="social-linkedin"><a class=" tooltip-top" target="_blank" href="#"
                                                    data-tooltip="LinkedIn"><i class="fa fa-linkedin"
                                                        aria-hidden="true"></i></a></li>
                                        </ul>
                                    </div>
                                    <br>
                                    <div class="mb-20">
                                        <a class="ttm-btn ttm-btn-size-xs ttm-btn-shape-square ttm-btn-style-fill ttm-btn-bgcolor-skincolor ttm-btn-color-white"
                                            href="{{ route('about') }}">READ MORE</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-xs-12 col-sm-12 col-md-6 col-lg-3 widget-area">
                            <div class="widget widget_nav_menu clearfix">
                                <h3 class="widget-title">Quick Links</h3>
                                <ul id="menu-footer-services">
                                    <li><a href="{{ route('about.services') }}">Customer Services</a></li>
                                    <li><a href="#">Department Services</a></li>
                                    <li><a href="{{ route('about') }}">About Company</a></li>
                                    <li><a href="#">Meet Our Experts</a></li>
                                    <li><a href="#">Contact Us</a></li>
                                </ul>
                            </div>
                        </div>
                        <div class="col-xs-12 col-sm-12 col-md-6 col-lg-3 widget-area">
                            <div class="widget widget_text clearfix">
                                <h3 class="widget-title">Latest News</h3>
                                <ul class="widget-post ttm-recent-post-list">
                                    @foreach($latest_blogs as $blog)    
                                    <li>
                                        <a href="{{ route('blogs.show', $blog) }}"><img src="{{ asset(imagePath($blog->image, 'blogs')) }}"
                                                alt="{{ $blog->title }}"></a>
                                        <span class="post-date">{{ $blog->created_at['year']. ' ' .$blog->created_at['month'] . ' ' .$blog->created_at['day'] }}</span>

                                        <a href="{{ route('blogs.show', $blog) }}">{{ Str::limit($blog->title, 50) }}</a>
                                    </li>
                                    @endforeach
                                </ul>
                            </div>
                        </div>
                        <div class="col-xs-12 col-sm-12 col-md-6 col-lg-3 widget-area">
                            <div class="widget flicker_widget clearfix">
                                <h3 class="widget-title">Our Branches</h3>
                                <div class="textwidget widget-text">
                                    <ul class="ttm-our-location-list">
                                        @foreach($footer_contacts as $contact)
                                        <li><i class="fa fa-map-marker"></i>{{ $contact->country }}, {{ $contact->address }} &nbsp</li>
                                        <li><i class="fa fa-phone"></i>{{ $contact->phone_number_one }}, {{ $contact->phone_number_two }}</li>

                                       @endforeach
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="bottom-footer-text ttm-textcolor-white">
                <div class="container">
                    <div class="row copyright">
                        <div class="col-md-12">
                            <div class="">
                                <span>Copyright © {{ date('Y') }}&nbsp;<a href="{{ route('home') }}">Franklin</a>. All rights reserved.</span>
                            </div>
                        </div>
                        <div class="col-md-12">
                            <ul id="menu-footer-menu" class="footer-nav-menu">
                                <li><a href="{{ route('about') }}">About Us</a></li>
                                <li><a href="{{ route('about.services') }}">Services</a></li>
                                <li><a href="{{ route('about') }}">Privacy</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </footer>
        <!--footer end-->

        <!--back-to-top start-->
        <a id="totop" href="#top">
            <i class="fa fa-angle-up"></i>
        </a>
        <!--back-to-top end-->

        </div><!-- page end -->


        <!-- Javascript -->

        <script src="{{ asset('frontend/js/jquery.min.js') }}"></script>
        <script src="{{ asset('frontend/js/tether.min.js') }}"></script>
        <script src="{{ asset('frontend/js/bootstrap.min.js') }}"></script>
        <script src="{{ asset('frontend/js/jquery.easing.js') }}"></script>
        <script src="{{ asset('frontend/js/jquery-waypoints.js') }}"></script>
        <script src="{{ asset('frontend/js/jquery-validate.js') }}"></script>
        <script src="{{ asset('frontend/js/owl.carousel.js') }}"></script>
        <script src="{{ asset('frontend/js/jquery.prettyPhoto.js') }}"></script>
        <script src="{{ asset('frontend/js/numinate.min6959.js?ver=4.9.3') }}"></script>
        <script src="{{ asset('frontend/js/main.js') }}"></script>

        <!-- Revolution Slider -->
        <script src="{{ asset('frontend/revolution/js/jquery.themepunch.tools.min.js') }}"></script>
        <script src="{{ asset('frontend/revolution/js/jquery.themepunch.revolution.min.js') }}"></script>
        <script src="{{ asset('frontend/revolution/js/slider.js') }}"></script>


        <!-- SLIDER REVOLUTION 5.0 EXTENSIONS  (Load Extensions only on Local File Systems !  The following part can be removed on Server for On Demand Loading) -->

        {{--  <script src="{{ asset('frontend/revolution/js/extensions/revolution.extension.actions.min.js') }}"></script>
        <script src="{{ asset('frontend/revolution/js/extensions/revolution.extension.carousel.min.js') }}"></script>
        <script src="{{ asset('frontend/revolution/js/extensions/revolution.extension.kenburn.min.js') }}"></script>
        <script src="{{ asset('frontend/revolution/js/extensions/revolution.extension.layeranimation.min.js') }}">
        </script>
        <script src="{{ asset('frontend/revolution/js/extensions/revolution.extension.migration.min.js') }}"></script>
        <script src="{{ asset('frontend/revolution/js/extensions/revolution.extension.navigation.min.js') }}"></script>
        <script src="{{ asset('frontend/revolution/js/extensions/revolution.extension.parallax.min.js') }}"></script>
        <script src="{{ asset('frontend/revolution/js/extensions/revolution.extension.slideanims.min.js') }}"></script>  --}}

        <!-- Javascript end-->
        @section('footerelements')
        @show
        </body>

        </html>

resources/views/frontend/partials/_map.blade.php
<!-- map-section -->
<div class="ttm-row map-section" style="margin-top:{{ $margin ?? '' }}px">
    <div class="container">
        <div class="row">
                <div class="col-md-12">
                    <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3532.378685517667!2d85.32096921506205!3d27.70559188279262!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x39eb19e3441f1b35%3A0x4a594a452f6c53f7!2sFranklin%20Education%20And%20Marketing%20Consultancy!5e0!3m2!1sen!2snp!4v1626530838760!5m2!1sen!2snp" width="{{ $width ?? 600 }}" height="{{ $height ?? 350 }}" style="border:0;" allowfullscreen="" loading="lazy"></iframe>
                 </div>
        </div>
    </div>
</div>
<!-- map-section end -->